apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: h8grh-674ln
  name: h8grh-674ln-infra
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: h8grh-674ln
      machine.openshift.io/cluster-api-machineset: h8grh-674ln-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: h8grh-674ln
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: h8grh-674ln-infra
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 32768
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: segment-sandbox-h8grh
          numCPUs: 8
          numCoresPerSocket: 4
          snapshot: ""
          template: h8grh-674ln-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: SDDC-Datacenter
            datastore: WorkloadDatastore
            folder: /SDDC-Datacenter/vm/Workloads/sandbox-h8grh
            resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources
            server: portal.vc.opentlc.com
