apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-py-oom
  name: demo-py-oom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-py-oom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-py-oom
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:52f987b597c5e2425cad791d32060cbdf8091150
        name: py-call-oom
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            memory: "20Mi"
status: {}
