apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: debug-toolbox
  name: debug-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-toolbox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debug-toolbox
    spec:
      containers:
      - image: registry.redhat.io/rhel7/rhel-tools
        command: ["sleep", "2d"]
        name: debug-toolbox
        resources: {}
status: {}
