apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: external-hostnet
  namespace: openshift-ingress-operator
spec:
  domain: demo.rhdemo.xyz
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 8081
      httpsPort: 8444
      statsPort: 8937
    type: HostNetwork
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved
  routeSelector:
    matchLabels:
     router: external-hn
replicas: 2
