apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-topology-anti-pod
  name: demo-topology-anti-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-topology-anti-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-topology-anti-pod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - demo-topology-anti-pod
            topologyKey: kubernetes.io/hostname
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:52f987b597c5e2425cad791d32060cbdf8091150
        name: py-http-call
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        resources: {}
status: {}
