apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-pod-aff-redis
  name: demo-pod-aff-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pod-aff-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-pod-aff-redis
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis
            topologyKey: kubernetes.io/hostname
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:52f987b597c5e2425cad791d32060cbdf8091150
        name: demo-pod-aff-redis
        resources: {}
status: {}

