apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: demo-app-test-alert
spec:
  egressIPs:
  - 192.168.162.155
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - test-alert
      - test-alert-2
      - test-application
