apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: zz-infra
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,zz-infra]}
  maxUnavailable: null
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/zz-infra: ""
  paused: false
